tasks = ['audio-classification',
         'automatic-speech-recognition',
         'conversational', 
         'feature-extraction', 
         'fill-mask', 
         'image-classification', 
         'image-segmentation', 
         'ner', 
         'object-detection', 
         'question-answering', 
         'sentiment-analysis', 
         'summarization', 
         'table-question-answering', 
         'text-classification', 
         'text-generation', 
         'text2text-generation', 
         'token-classification', 
         'translation', 
         'visual-question-answering', 
         'vqa', 
         'zero-shot-classification', 
         'zero-shot-image-classification',
         'translation_XX_to_YY']
         